#include "tac_dx11_shader_preprocess.h" // self-inc

#include "tac-std-lib/string/tac_string.h" // String
#include "tac-std-lib/preprocess/tac_preprocessor.h"

namespace Tac::Render
{
  static int GetPadByteCount( const StringView& line )
  {
    String numberStr;

    // Compiler literally decides to skip the string if we leave out these curly brackets
    for( char c : line )
    {
      if( IsDigit( c ) )
      {
        numberStr += c;
      }
    }

    TAC_ASSERT( !numberStr.empty() );

    const int padByteCount = Atoi( numberStr );
    TAC_ASSERT( padByteCount );
    TAC_ASSERT( padByteCount % 4 == 0 ); // <-- why?
    return padByteCount;
  }

  Optional<String> ShaderPreprocessorPadding::Preprocess( const StringView line, Errors& )
  {
    if( !line.contains("TAC_PAD_BYTES") )
      return {};

    const int iPad = line.find( "TAC_PAD_BYTES" );
    const int padByteCount = GetPadByteCount( line );
    const int count = mCounter++;

    const String spaces( iPad, ' ' );

    String result;
    for( int i = 0; i < padByteCount / 4; ++i )
    {
      const char* separator = i ? "\n" : "";
      const String varName = "pad" + ToString( count );

      result += separator;
      result += spaces + "uint ";
      result += varName;
      result += "; // Padding autogenerated by " + String( __FUNCTION__ );
    }

    return result;
  }
} // namespace Tac::Render

