// The purpose of this file is to coordinate/implement the synchronization of the window system
// between the game logic ("sim") and platform ("sys") threads.

#pragma once

#include "tac-std-lib/string/tac_string.h"
#include "tac-std-lib/string/tac_string_view.h"
#include "tac-std-lib/math/tac_vector2i.h"
#include "tac-std-lib/containers/tac_array.h"

#include "tac-engine-core/window/tac_window_handle.h"
#include "tac-rhi/render3/tac_render_api.h"

namespace Tac { struct Errors; }

namespace Tac
{
  inline const int kDesktopWindowCapacity = 100;
}

namespace Tac::WindowBackend
{

  // +------------------------------------------------------------+
  // |                          TODO                              |
  // +------------------------------------------------------------+
  // | handle destroying and creating windows not having the same |
  // | id in the same frame                                       |
  // +------------------------------------------------------------+

  struct SysApi
  {
    // Handle desktop event queue on the platform thread
    void ApplyBegin();
    void SetWindowCreated( WindowHandle, const void*, StringView, v2i pos, v2i size, Errors& );
    void SetWindowDestroyed( WindowHandle );
    void SetWindowIsVisible( WindowHandle, bool );
    void SetWindowSize( WindowHandle, v2i );
    void SetWindowPos( WindowHandle, v2i );
    v2i  GetWindowPos( WindowHandle );
    void ApplyEnd();

    // On the system thread, synchronize and execute requests generated by the simulation thread
    void Sync( Errors& );

    static bool mIsRendererEnabled;
  };

  inline Render::TexFmt sTexFmt = Render::TexFmt::kRGBA16F;

  // Sim thread functions:

  struct SimApi
  {
    // Synchronize window updates generated on the sys thread
    void Sync();
  };
}

