#include "tac_hlsl_preprocess_register.h" // self-inc

#include "tac-std-lib/string/tac_string.h" // String
#include "tac-std-lib/dataprocess/tac_text_parser.h" // ParseData
#include "tac-std-lib/containers/tac_array.h" // Array

namespace Tac::Render
{
  // -----------------------------------------------------------------------------------------------

  struct VirtualRegisterBindingSpace
  {
    const char* mType[ 10 ] {};
    char        mLetter     {};
  };

  static const VirtualRegisterBindingSpace sBindings[]
  {
    VirtualRegisterBindingSpace // Shader Resource Views
    {
      .mType{ "Texture2D", "Texture3D", "TextureCube", "Buffer" },
      .mLetter{ 't' },
    },
    VirtualRegisterBindingSpace // Unordered Access Views
    {
      .mType{ "RWBuffer" },
      .mLetter{ 'u' },
    },
    VirtualRegisterBindingSpace // Constant Buffer Views
    {
      .mType{ "cbuffer", "ConstantBuffer" },
      .mLetter{ 'b' },
    },
    VirtualRegisterBindingSpace // Samplers
    {
      .mType{ "SamplerState", "sampler" },
      .mLetter{ 's' },
    },
  };

  static auto GetRegisterCount( StringView line ) -> int
  {
      const int iOpen { line.find( '[' ) };
      const int iClose { line.find( ']' ) };
      if( iOpen == line.npos || iClose == line.npos )
        return 1;
      return ( int )ParseData( line.data() + iOpen + 1,
                               line.data() + iClose ).EatFloat().GetValue();
  }

  static char GetResourceLetter( StringView line )
  {
    const int iOpenParen{ line.find( '(' ) };
    const int iCloseParen{ line.find( ')' ) };
    if( iOpenParen != StringView::npos &&
        iCloseParen != StringView::npos )
    {
      ParseData parseData( line.data() + iOpenParen + 1, line.data() + iCloseParen );
      parseData.EatWhitespace();
      char c{ *parseData.EatByte() };
      bool found{};
      for( const VirtualRegisterBindingSpace& binding : sBindings )
        found |= ( binding.mLetter == c );
      TAC_ASSERT( found );
      return c;
    }

    ParseData parseData( line );
    parseData.EatWhitespace();

    // https://learn.microsoft.com/en-us/windows/win32/direct3d12/resource-binding-in-hlsl
    // HLSL programs can assign bindings to the virtual “register” binding space
    // t# for SRVs, u# for UAVs, b# for CBVs, s# for samplers

    for( const VirtualRegisterBindingSpace& binding : sBindings )
      for( const char* type : binding.mType )
        if( type && parseData.PeekStringExpected( type )  )
          return binding.mLetter;

    return ( char )0;
  }

  // -----------------------------------------------------------------------------------------------

  // c - The resource type name ( 
  // n - The resources count
  // 
  // ex 1: Texture2D shadowMaps[ 4 ] : TAC_AUTO_REGISTER;
  //       This results in Add( 't', 4 )
  //
  // ex 2: cbuffer CBufferLights : TAC_AUTO_REGISTER;
  //       This results in Add( 'b', 1 )
  // 
  // The return value is the register assigned to each resource.
  auto HLSLLinePreprocessorRegister::Add( char c, int n ) -> int
  {
    const int iResource { mLetterCounts[ c ] };
    mLetterCounts[ c ] += n;
    return iResource;
  }

  auto HLSLLinePreprocessorRegister::Preprocess( Input input, Errors& ) -> Optional< String >
  {
    const StringView line{input.mLine};
    const StringView autoRegister { "TAC_AUTO_REGISTER" };
    const int iReplaceBegin { line.find( autoRegister ) };
    if( iReplaceBegin == line.npos )
      return {};

    int iReplaceEnd{ iReplaceBegin + autoRegister.size() };
    const int iSemicolin{ line.find_first_of( ';' ) };
    const int iCloseParen{ line.find_first_of( ')' ) };
    if( iCloseParen != StringView::npos && iCloseParen < iSemicolin )
    {
      iReplaceEnd = iCloseParen + 1;
    }

    const int regCount { GetRegisterCount( line ) };
    const char letter { GetResourceLetter( line ) };
    TAC_ASSERT_MSG( letter, String()
                    + "Cant figure out TAC_AUTO_REGISTER in "
                    + input.mFile + ":" + ToString( input.mLineNumber )
                    + "\n" + input.mLine + "\n"  );

    const int iResource { Add( letter, regCount ) };
    const String registerStr {
      String() + "register( " + ToString( letter ) + ToString( iResource ) + " )" };

    String result;
    result += "// Autogenerated register from ";
    result += __FUNCTION__;
    result += '\n';
    result += line.substr( 0, iReplaceBegin ); // everthing before TAC_AUTO_REGISTER
    result += registerStr;
    result += line.substr( iReplaceEnd ); // everything after TAC_AUTO_REGISTER
    return result;
  }

} // namespace Tac::Render



