#include "tac-std-lib/meta/tac_meta_composite.h"
#include "tac-std-lib/math/tac_math_meta.h"
#include "tac-std-lib/math/tac_vector2.h"
#include "tac-std-lib/math/tac_vector3.h"
#include "tac-std-lib/math/tac_vector4.h"
#include "tac-std-lib/math/tac_matrix3.h"
#include "tac-std-lib/math/tac_matrix4.h"

namespace Tac
{

  TAC_META_REGISTER_COMPOSITE_BEGIN( v2 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v2, x )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v2, y )
    TAC_META_REGISTER_COMPOSITE_END( v2 );

  TAC_META_REGISTER_COMPOSITE_BEGIN( v3 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v3, x )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v3, y )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v3, z )
    TAC_META_REGISTER_COMPOSITE_END( v3 );

  TAC_META_REGISTER_COMPOSITE_BEGIN( v4 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v4, x )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v4, y )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v4, z )
    TAC_META_REGISTER_COMPOSITE_MEMBER( v4, w )
    TAC_META_REGISTER_COMPOSITE_END( v4 );

  TAC_META_REGISTER_COMPOSITE_BEGIN( m3 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m00 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m01 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m02 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m10 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m11 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m12 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m20 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m21 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m3, m22 )
    TAC_META_REGISTER_COMPOSITE_END( m3 );

  TAC_META_REGISTER_COMPOSITE_BEGIN( m4 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m00 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m01 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m02 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m03 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m10 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m11 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m12 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m13 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m20 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m21 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m22 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m23 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m30 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m31 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m32 )
    TAC_META_REGISTER_COMPOSITE_MEMBER( m4, m33 )
    TAC_META_REGISTER_COMPOSITE_END( m4 );

} // namespace Tac

