
cloc                                                                                         ^
  --hide-rate ../src                                                                         ^
  --exclude-dir=thirdparty,autogenerated,tac-jppt,game-pbrt,game-weekendtrace                ^
  --exclude-ext=natvis,md,txt                                                                ^
  --found=cloc_found.txt                                                                     ^
  --ignored=cloc_ignored.txt                                                                 ^
  -out=cloc_out.txt

